# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

"""
LLM-powered insight generation for evaluation reports.

Reads a report.md file, sends it to Bedrock, and writes insights.md
to the same report directory.
"""

from pathlib import Path
from typing import Optional

from uaef.config import get_config
from uaef.insights.prompts import COMPARISON_PROMPT, SINGLE_RUN_PROMPT
from uaef.llm_judge.bedrock_client import BedrockClient
from uaef.logging import get_logger

logger = get_logger(__name__)


def generate_insights(
    report_dir: str,
    *,
    report_type: Optional[str] = None,
    model_id: Optional[str] = None,
) -> str:
    """
    Generate LLM-powered insights for an existing report.

    Reads report.md from the given report directory, sends it to Bedrock
    for analysis, and writes insights.md to the same directory.

    Args:
        report_dir: Path to the report directory (must contain report.md)
        report_type: "single" or "comparison" (auto-detected if None)
        model_id: Override the model ID from config (optional)

    Returns:
        Path to the generated insights.md file

    Examples:
        >>> from uaef.insights import generate_insights
        >>> insights_path = generate_insights("output/reports/full_report_20260602_125549")
    """
    report_dir = Path(report_dir)
    report_path = report_dir / "report.md"

    if not report_path.exists():
        raise FileNotFoundError(f"No report.md found in {report_dir}")

    report_content = report_path.read_text(encoding="utf-8")

    # Auto-detect report type
    if report_type is None:
        if "Comparison Report" in report_content or "Changes from Baseline" in report_content:
            report_type = "comparison"
        else:
            report_type = "single"

    logger.info(f"Generating {report_type} insights for {report_dir}")

    # Select prompt
    if report_type == "comparison":
        prompt = COMPARISON_PROMPT.format(report_content=report_content)
    else:
        prompt = SINGLE_RUN_PROMPT.format(report_content=report_content)

    # Call Bedrock
    config = get_config()
    insight_config = config.insight
    effective_model = model_id or insight_config.model_id

    client = BedrockClient(
        region=config.aws.region,
        retry_attempts=insight_config.retry_attempts,
        retry_delay=insight_config.retry_delay,
    )

    response_text, _metadata = client.invoke_model(
        model_id=effective_model,
        prompt=prompt,
        temperature=insight_config.temperature,
        max_tokens=insight_config.max_tokens,
    )

    # Write insights.md
    insights_path = report_dir / "insights.md"
    header = f"# Insights ({report_type.title()} Analysis)\n\n"
    header += f"*Generated by LLM ({effective_model})*\n\n---\n\n"
    insights_path.write_text(header + response_text, encoding="utf-8")

    logger.info(f"Insights saved to {insights_path}")
    return str(insights_path)
